// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func initDB() (*DB, error) {
	options := provideOptions()
	db, err := (*Options).ToDB(options)
	if err != nil {
		return nil, err
	}
	return db, nil
}
